# Generated by Django 3.0.8 on 2020-07-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200711_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
