# Generated by Django 3.0.8 on 2020-07-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
    ]
